/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Admin;
import model.Answer;
import model.Lesson;
import model.Question;
import model.Student;
import model.StudyMaterial;

public class Window extends javax.swing.JFrame {

    int studentCounter = 1;
    Student student;
    StudyMaterial sm;
    Lesson lesson;
    Question question;
    Answer answer;
    ArrayList<Student> listStudents = new ArrayList<>();
    Admin admin = Admin.getInstance();
    int posi;

    public Window() {
        initComponents();
        Admin.initializeAdmin("1", "Jose", "josea@gmail.com", "1234567890");
        student = new Student();
        fieldIdStudent.setText(String.valueOf(studentCounter));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldNameStudent = new javax.swing.JTextField();
        fieldEmailStudent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        fieldIdStudent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnModifyStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentArea = new javax.swing.JTextArea();
        studentsCombo = new javax.swing.JComboBox<>();
        btnPrintAllStudents = new javax.swing.JButton();
        btnRemoveStudent = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fieldNameLesson = new javax.swing.JTextField();
        fieldDescriptionLesson = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAddLesson = new javax.swing.JButton();
        fieldIdLessons = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldStudyMaterial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        studentLessonsCombo = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fieldThemeStudyMaterial = new javax.swing.JTextField();
        fieldContentStudyMaterial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThemeStudyMaterial = new javax.swing.JButton();
        btnPrintAllStudyMaterial = new javax.swing.JButton();
        btnModifyLesson = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonsArea = new javax.swing.JTextArea();
        lessonsCombo = new javax.swing.JComboBox<>();
        btnRemoveLesson = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        fieldQuestion2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnAddQuestion = new javax.swing.JButton();
        fieldIdQuestions = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        studentQuestionsCombo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        lessonsQuestionsCombo = new javax.swing.JComboBox<>();
        fieldCorrectAnswer = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fieldQuestion3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fieldQuestion4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        statementQuestion = new javax.swing.JTextField();
        btnPrintQuestions = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        questionsArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fieldIdAnswer = new javax.swing.JTextField();
        questionsAnswersCombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        studentAnswersCombo = new javax.swing.JComboBox<>();
        lessonsAnswersCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        fieldAnswerContent = new javax.swing.JTextField();
        btnAddQuestion1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        answersArea = new javax.swing.JTextArea();
        btnPrintQuestions1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cooltext467253845339598.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Students"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");

        fieldNameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameStudentActionPerformed(evt);
            }
        });

        fieldEmailStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailStudentActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email:");

        btnAddStudent.setBackground(new java.awt.Color(51, 255, 51));
        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStudent.setText("Add ");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        fieldIdStudent.setEnabled(false);
        fieldIdStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdStudentActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID:");

        btnModifyStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnModifyStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifyStudent.setText("Modify");
        btnModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldEmailStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldEmailStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnModifyStudent))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        studentArea.setColumns(20);
        studentArea.setRows(5);
        jScrollPane1.setViewportView(studentArea);

        studentsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsComboActionPerformed(evt);
            }
        });

        btnPrintAllStudents.setBackground(new java.awt.Color(51, 255, 51));
        btnPrintAllStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrintAllStudents.setText("Print All");
        btnPrintAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllStudentsActionPerformed(evt);
            }
        });

        btnRemoveStudent.setBackground(new java.awt.Color(255, 51, 51));
        btnRemoveStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveStudent.setText("Remove");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(studentsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrintAllStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrintAllStudents))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveStudent)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Students", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Lessons"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Lesson Name:");

        fieldNameLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameLessonActionPerformed(evt);
            }
        });

        fieldDescriptionLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescriptionLessonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Description:");

        btnAddLesson.setBackground(new java.awt.Color(51, 255, 51));
        btnAddLesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLesson.setText("Add ");
        btnAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLessonActionPerformed(evt);
            }
        });

        fieldIdLessons.setEnabled(false);
        fieldIdLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdLessonsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("ID:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Study Material:");

        fieldStudyMaterial.setEnabled(false);
        fieldStudyMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStudyMaterialActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Student:");

        studentLessonsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLessonsComboActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Study Material"));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Theme:");

        fieldThemeStudyMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldThemeStudyMaterialActionPerformed(evt);
            }
        });

        fieldContentStudyMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContentStudyMaterialActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Content:");

        btnThemeStudyMaterial.setBackground(new java.awt.Color(51, 255, 51));
        btnThemeStudyMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemeStudyMaterial.setText("Add ");
        btnThemeStudyMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeStudyMaterialActionPerformed(evt);
            }
        });

        btnPrintAllStudyMaterial.setBackground(new java.awt.Color(51, 255, 51));
        btnPrintAllStudyMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrintAllStudyMaterial.setText("Print Study Material");
        btnPrintAllStudyMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllStudyMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnThemeStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrintAllStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldThemeStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldContentStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldThemeStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldContentStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemeStudyMaterial)
                    .addComponent(btnPrintAllStudyMaterial))
                .addContainerGap())
        );

        btnModifyLesson.setBackground(new java.awt.Color(255, 255, 255));
        btnModifyLesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifyLesson.setText("Modify");
        btnModifyLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(btnAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifyLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldIdLessons, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentLessonsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNameLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldDescriptionLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(studentLessonsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldIdLessons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldNameLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldDescriptionLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldStudyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLesson)
                    .addComponent(btnModifyLesson))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lessonsArea.setColumns(20);
        lessonsArea.setRows(5);
        jScrollPane3.setViewportView(lessonsArea);

        lessonsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonsComboActionPerformed(evt);
            }
        });

        btnRemoveLesson.setBackground(new java.awt.Color(255, 51, 51));
        btnRemoveLesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveLesson.setText("Remove");
        btnRemoveLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLessonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Select a Lesson:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lessonsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lessonsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveLesson)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Lessons", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Lessons"));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Answer 2");

        fieldQuestion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuestion2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Correct Answer:");

        btnAddQuestion.setBackground(new java.awt.Color(51, 255, 51));
        btnAddQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddQuestion.setText("Add ");
        btnAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuestionActionPerformed(evt);
            }
        });

        fieldIdQuestions.setEnabled(false);
        fieldIdQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdQuestionsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("ID:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Student:");

        studentQuestionsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentQuestionsComboActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Lesson:");

        fieldCorrectAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCorrectAnswerActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Answer 3");

        fieldQuestion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuestion3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Answer 4");

        fieldQuestion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuestion4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Statement");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(lessonsQuestionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(studentQuestionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldQuestion3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(fieldIdQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statementQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(fieldCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(studentQuestionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lessonsQuestionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIdQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(statementQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldCorrectAnswer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addComponent(fieldQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(fieldQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddQuestion)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnPrintQuestions.setBackground(new java.awt.Color(51, 255, 51));
        btnPrintQuestions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrintQuestions.setText("Print Questions");
        btnPrintQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintQuestionsActionPerformed(evt);
            }
        });

        questionsArea.setColumns(20);
        questionsArea.setRows(5);
        jScrollPane4.setViewportView(questionsArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPrintQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Questions", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Answers"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        fieldIdAnswer.setEnabled(false);

        questionsAnswersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionsAnswersComboActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Question:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Lesson:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Student:");

        studentAnswersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAnswersComboActionPerformed(evt);
            }
        });

        lessonsAnswersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonsAnswersComboActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Answer Content:");

        fieldAnswerContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAnswerContentActionPerformed(evt);
            }
        });

        btnAddQuestion1.setBackground(new java.awt.Color(51, 255, 51));
        btnAddQuestion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddQuestion1.setText("Add ");
        btnAddQuestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuestion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(lessonsAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(studentAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(questionsAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAnswerContent, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldIdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(studentAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lessonsAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(questionsAnswersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldIdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAnswerContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(btnAddQuestion1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        answersArea.setColumns(20);
        answersArea.setRows(5);
        jScrollPane5.setViewportView(answersArea);

        btnPrintQuestions1.setBackground(new java.awt.Color(51, 255, 51));
        btnPrintQuestions1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrintQuestions1.setText("Print Answers");
        btnPrintQuestions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintQuestions1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrintQuestions1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnPrintQuestions1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Answers", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(188, 188, 188))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameStudentActionPerformed

    private void fieldEmailStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        student = new Student();
        student.setId(fieldIdStudent.getText());
        student.setName(fieldNameStudent.getText());
        student.setEmail(fieldEmailStudent.getText());
        listStudents.add(student);
        JOptionPane.showMessageDialog(null, "Student added");
        studentCounter = studentCounter + 1;
        fieldIdStudent.setText(String.valueOf(studentCounter));
        studentsCombo.addItem(student.getName());
        studentLessonsCombo.addItem(student.getName());
        studentQuestionsCombo.addItem(student.getName());
        studentAnswersCombo.addItem(student.getName());
        cleanStudentsField();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void fieldIdStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdStudentActionPerformed

    private void btnPrintAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllStudentsActionPerformed
        studentArea.setText("STUDENTS:");
        for (int i = 0; i < listStudents.size(); i++) {
            studentArea.append("\n\nId: " + listStudents.get(i).getId());
            studentArea.append("\nName: " + listStudents.get(i).getName());
            studentArea.append("\nEmail: " + listStudents.get(i).getEmail());
        }
    }//GEN-LAST:event_btnPrintAllStudentsActionPerformed

    private void studentsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsComboActionPerformed
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                studentArea.setText("Student: " + student.getId());
                studentArea.append("\nName: " + student.getName());
                studentArea.append("\nEmail: " + student.getEmail());
            }
        }
    }//GEN-LAST:event_studentsComboActionPerformed

    private void fieldThemeStudyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldThemeStudyMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldThemeStudyMaterialActionPerformed

    private void fieldContentStudyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContentStudyMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContentStudyMaterialActionPerformed

    private void btnThemeStudyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeStudyMaterialActionPerformed
        sm = new StudyMaterial();
        sm = admin.createStudyMaterial(fieldThemeStudyMaterial.getText(), fieldContentStudyMaterial.getText());
        JOptionPane.showMessageDialog(null, "Study Material Added");
        fieldStudyMaterial.setText(sm.getTheme());
    }//GEN-LAST:event_btnThemeStudyMaterialActionPerformed

    private void btnPrintAllStudyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllStudyMaterialActionPerformed
        sm.printStudyMaterial(lessonsArea);
    }//GEN-LAST:event_btnPrintAllStudyMaterialActionPerformed

    private void fieldNameLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameLessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameLessonActionPerformed

    private void fieldDescriptionLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescriptionLessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescriptionLessonActionPerformed

    private void btnAddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLessonActionPerformed
        lesson = new Lesson();
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentLessonsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                lesson = admin.createLesson(fieldNameLesson.getText(), fieldDescriptionLesson.getText(), sm);
                student.listLesson.add(lesson);
                JOptionPane.showMessageDialog(null, "Lesson Added");

            }
        }
    }//GEN-LAST:event_btnAddLessonActionPerformed

    private void fieldIdLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdLessonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdLessonsActionPerformed

    private void fieldStudyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStudyMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStudyMaterialActionPerformed

    private void fieldQuestion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuestion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuestion2ActionPerformed

    private void btnAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuestionActionPerformed
        question = new Question();
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentQuestionsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    if (lessonsQuestionsCombo.getSelectedItem().toString().equals(student.listLesson.get(p).getName())) {
                        lesson = student.listLesson.get(p);
                        question.addAnswer(fieldQuestion2.getText());
                        question.addAnswer(fieldQuestion3.getText());
                        question.addAnswer(fieldQuestion4.getText());
                        question = admin.createQuestion(statementQuestion.getText(), fieldCorrectAnswer.getText());
                        lesson.listQuestions.add(question);
                        JOptionPane.showMessageDialog(null, "Question Added");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAddQuestionActionPerformed

    private void fieldIdQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdQuestionsActionPerformed

    private void btnPrintQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintQuestionsActionPerformed
        lesson.printQuestions(questionsArea);
    }//GEN-LAST:event_btnPrintQuestionsActionPerformed

    private void fieldCorrectAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCorrectAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCorrectAnswerActionPerformed

    private void studentQuestionsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentQuestionsComboActionPerformed
        lessonsQuestionsCombo.removeAllItems();
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentQuestionsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    lessonsQuestionsCombo.addItem(student.listLesson.get(p).getName());
                }
            }
        }
    }//GEN-LAST:event_studentQuestionsComboActionPerformed

    private void studentAnswersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAnswersComboActionPerformed
        lessonsAnswersCombo.removeAllItems();
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentAnswersCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    lessonsAnswersCombo.addItem(student.listLesson.get(p).getName());
                }
            }
        }
    }//GEN-LAST:event_studentAnswersComboActionPerformed

    private void lessonsAnswersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonsAnswersComboActionPerformed
        questionsAnswersCombo.removeAllItems();
        for (int i = 0; i < student.listLesson.size(); i++) {
            if (lessonsAnswersCombo.getSelectedItem().toString().equals(student.listLesson.get(i).getName())) {
                lesson = student.listLesson.get(i);
                for (int p = 0; p < lesson.listQuestions.size(); p++) {
                    questionsAnswersCombo.addItem(lesson.listQuestions.get(p).getName());
                }
            }
        }
    }//GEN-LAST:event_lessonsAnswersComboActionPerformed

    private void fieldAnswerContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAnswerContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAnswerContentActionPerformed

    private void questionsAnswersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionsAnswersComboActionPerformed
        for (int i = 0; i < lesson.listQuestions.size(); i++) {
            if (questionsAnswersCombo.getSelectedItem().toString().equals(lesson.listQuestions.get(i).getName())) {
                question = lesson.listQuestions.get(i);
            }
        }
    }//GEN-LAST:event_questionsAnswersComboActionPerformed

    private void btnAddQuestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuestion1ActionPerformed
        answer = new Answer();
        answer.setContent(fieldAnswerContent.getText());
        question.listAnswers.add(answer);
    }//GEN-LAST:event_btnAddQuestion1ActionPerformed

    private void btnPrintQuestions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintQuestions1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintQuestions1ActionPerformed

    private void fieldQuestion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuestion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuestion3ActionPerformed

    private void fieldQuestion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuestion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuestion4ActionPerformed

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                listStudents.remove(i);
                studentsCombo.removeItemAt(i);
                studentAnswersCombo.removeItemAt(i);
                studentQuestionsCombo.removeItemAt(i);
                studentLessonsCombo.removeItemAt(i);
            }
        }
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void lessonsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonsComboActionPerformed

    }//GEN-LAST:event_lessonsComboActionPerformed

    private void studentLessonsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLessonsComboActionPerformed
        
        lessonsCombo.removeAllItems();
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentLessonsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    lessonsCombo.addItem(student.listLesson.get(p).getName());
                }
            }
        }
        student.printLessons(lessonsArea);
    }//GEN-LAST:event_studentLessonsComboActionPerformed

    private void btnRemoveLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLessonActionPerformed
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentLessonsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    if (lessonsCombo.getSelectedItem().toString().equals(student.listLesson.get(p).getName())) {
                        student.listLesson.remove(p);
                        lessonsCombo.removeItemAt(p);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRemoveLessonActionPerformed

    private void btnModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyStudentActionPerformed
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                listStudents.get(i).setName(fieldNameStudent.getText());
                listStudents.get(i).setEmail(fieldEmailStudent.getText());
                posi = studentsCombo.getSelectedIndex();
                studentsCombo.insertItemAt(fieldNameStudent.getText(), posi);
                studentsCombo.removeItemAt(posi + 1);
                studentsCombo.setSelectedIndex(posi);

                studentLessonsCombo.insertItemAt(fieldNameStudent.getText(), posi);
                studentLessonsCombo.removeItemAt(posi + 1);
                studentLessonsCombo.setSelectedIndex(posi);

                studentQuestionsCombo.insertItemAt(fieldNameStudent.getText(), posi);
                studentQuestionsCombo.removeItemAt(posi + 1);
                studentQuestionsCombo.setSelectedIndex(posi);

                JOptionPane.showMessageDialog(null, "Student Modified");
            }
        }
    }//GEN-LAST:event_btnModifyStudentActionPerformed

    private void btnModifyLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyLessonActionPerformed
        for (int i = 0; i < listStudents.size(); i++) {
            if (studentLessonsCombo.getSelectedItem().toString().equals(listStudents.get(i).getName())) {
                student = listStudents.get(i);
                for (int p = 0; p < student.listLesson.size(); p++) {
                    if (lessonsCombo.getSelectedItem().toString().equals(student.listLesson.get(p).getName())) {
                        student.listLesson.get(p).setName(fieldNameLesson.getText());
                        student.listLesson.get(p).setDescription(fieldDescriptionLesson.getText());
                        student.listLesson.get(p).setMaterial(sm);

                        posi = lessonsCombo.getSelectedIndex();
                        lessonsCombo.insertItemAt(fieldNameLesson.getText(), posi);
                        lessonsCombo.removeItemAt(posi + 1);
                        lessonsCombo.setSelectedIndex(posi);
                        
                        JOptionPane.showMessageDialog(null, "Lesson Modified");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnModifyLessonActionPerformed

    public void cleanStudentsField() {
        fieldNameStudent.setText("");
        fieldEmailStudent.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answersArea;
    private javax.swing.JButton btnAddLesson;
    private javax.swing.JButton btnAddQuestion;
    private javax.swing.JButton btnAddQuestion1;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnModifyLesson;
    private javax.swing.JButton btnModifyStudent;
    private javax.swing.JButton btnPrintAllStudents;
    private javax.swing.JButton btnPrintAllStudyMaterial;
    private javax.swing.JButton btnPrintQuestions;
    private javax.swing.JButton btnPrintQuestions1;
    private javax.swing.JButton btnRemoveLesson;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnThemeStudyMaterial;
    private javax.swing.JTextField fieldAnswerContent;
    private javax.swing.JTextField fieldContentStudyMaterial;
    private javax.swing.JTextField fieldCorrectAnswer;
    private javax.swing.JTextField fieldDescriptionLesson;
    private javax.swing.JTextField fieldEmailStudent;
    private javax.swing.JTextField fieldIdAnswer;
    private javax.swing.JTextField fieldIdLessons;
    private javax.swing.JTextField fieldIdQuestions;
    private javax.swing.JTextField fieldIdStudent;
    private javax.swing.JTextField fieldNameLesson;
    private javax.swing.JTextField fieldNameStudent;
    private javax.swing.JTextField fieldQuestion2;
    private javax.swing.JTextField fieldQuestion3;
    private javax.swing.JTextField fieldQuestion4;
    private javax.swing.JTextField fieldStudyMaterial;
    private javax.swing.JTextField fieldThemeStudyMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> lessonsAnswersCombo;
    private javax.swing.JTextArea lessonsArea;
    private javax.swing.JComboBox<String> lessonsCombo;
    private javax.swing.JComboBox<String> lessonsQuestionsCombo;
    private javax.swing.JComboBox<String> questionsAnswersCombo;
    private javax.swing.JTextArea questionsArea;
    private javax.swing.JTextField statementQuestion;
    private javax.swing.JComboBox<String> studentAnswersCombo;
    private javax.swing.JTextArea studentArea;
    private javax.swing.JComboBox<String> studentLessonsCombo;
    private javax.swing.JComboBox<String> studentQuestionsCombo;
    private javax.swing.JComboBox<String> studentsCombo;
    // End of variables declaration//GEN-END:variables
}
